### ISSUE TITLE
FYI. There is a warning about crypto version being slow

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [blha303/iviewdl#12]
I noticed a warning about the crypto version on my machine (linux mint 18) potentially being out of date and slow 

The version was 1.2.3

However, after upgrading to the latest version of the cryptography lib for Python (2.7) there were other warnings, which required OpenSSL to be installed and after both were installed, unfortunately iviewdl.py had problems, which seemed to be related to ascii encoding of the responses (probably to URL requests)

So my only option was to rollback the changes, which in the end required me to re-install python 

I'm going to retest on Linux Mint 19 Mate, to confirm its stable with whatever version of Python cypto is installed by default in Linux Mint

I'll update this issue when I can confirm its OK in Linux Mint 19 (and see what version of cryptography is installed)

**Comment by blha303** [comment]
Hi, warnings aren't really worth worrying about, lots of programs use warnings to pass on information. OpenSSL is one of those libraries where things depend on a particular version, and updating it just because a program says so is very likely to break a lot of other things, as you saw. Trying to clear all warnings from a program is usually a futile endeavour to be honest, most of the time it's much more useful to redirect stderr to a log file or find some parameter to disable the extraneous warnings. Thanks for the issue though, you're welcome to suggest further changes.

**Comment by blha303** [comment]
In https://github.com/blha303/iviewdl/blob/master/new_iviewdl.py I've hidden all ffmpeg warnings, they were annoying. Sorry for dismissing your feedback earlier, it's appreciated.
